version: '3'

# Define services
services:

  # Stock API Service
  stock-api:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./stock-api/Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    environment:
      ALPHA_APIKEY: ${ALPHA_APIKEY}

  # Encryption API Service
  encryption-api:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./encryption-api/Dockerfile
    ports:
      - "8081:8081" # Forward the exposed port 8081 on the container to port 8081 on the host machine
    restart: unless-stopped
